### ISSUE TITLE
好用，建议增加302地址缓存

### ISSUE THREAD

**Issue by ys-lmh** [xifo-wu/media-server-302#2]
这个项目的302转换设置简单好用。播放同一部片看日志好像会有几次获取重定向链接的请求，建议增加缓存到内存里，短时间内同个地址可以用缓存的302地址以节省时间。

**Comment by xifo-wu** [comment]
安排上了。 更新到 xifowu/media-server-302:latest 或者 xifowu/media-server-302:v1.1.0 就行。
